"""empty message

Revision ID: f838bfdfdf98
Revises: 
Create Date: 2024-12-25 14:29:52.328520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f838bfdfdf98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_playlist', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('segment_length', sa.Integer(), nullable=False),
    sa.Column('is_recording', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_id'), 'camera', ['id'], unique=False)
    op.create_index(op.f('ix_camera_name'), 'camera', ['name'], unique=False)
    op.create_table('audiostream',
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('codec', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_base_num', sa.Integer(), nullable=False),
    sa.Column('time_base_den', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('layout_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('format_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audiostream_camera_id'), 'audiostream', ['camera_id'], unique=False)
    op.create_table('videostream',
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('codec', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_base_num', sa.Integer(), nullable=False),
    sa.Column('time_base_den', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('sample_aspect_ratio_num', sa.Integer(), nullable=False),
    sa.Column('sample_aspect_ratio_den', sa.Integer(), nullable=False),
    sa.Column('framerate', sa.Integer(), nullable=False),
    sa.Column('gop_size', sa.Integer(), nullable=False),
    sa.Column('pix_fmt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videostream_camera_id'), 'videostream', ['camera_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videostream_camera_id'), table_name='videostream')
    op.drop_table('videostream')
    op.drop_index(op.f('ix_audiostream_camera_id'), table_name='audiostream')
    op.drop_table('audiostream')
    op.drop_index(op.f('ix_camera_name'), table_name='camera')
    op.drop_index(op.f('ix_camera_id'), table_name='camera')
    op.drop_table('camera')
    # ### end Alembic commands ###
